### ISSUE TITLE
English Documentation will be good to have.

### ISSUE THREAD

**Issue by mcuee** [askn37/UPDI4AVR-USB#7]
English Documentation will be good to have.
* https://github.com/avrdudes/avrdude/discussions/1878#discussioncomment-10310693

**Comment by askn37** [comment]
The English front page (README) can be viewed here:

https://github.com/askn37/UPDI4AVR-USB/blob/main/README_en.md
https://github.com/askn37/UPDI4AVR-USB/tree/main/hex/updi4avr-usb

As a general rule, we plan to post other documentation on the Wiki to avoid bloating the repository.
Currently, some documentation is released as experimental and may change significantly in the future.

https://github.com/askn37/UPDI4AVR-USB/wiki
https://github.com/askn37/UPDI4AVR-USB/wiki/How-to-read-DEBUG=1-mode
https://github.com/askn37/UPDI4AVR-USB/wiki/Peripheral-Discrete-Circuits

**Comment by mcuee** [comment]
Thanks for the info.

Probably the default page should be in English and then the Japanese Page is the secondary.

**Comment by askn37** [comment]
Commit https://github.com/askn37/UPDI4AVR-USB/commit/d76c23b1e6b96a15138b3ab1a934fefd73e6d299 : The front page has been swapped out and the English documentation has been replaced as the default.

**Comment by askn37** [comment]
Everything has been dealt with except the Wiki so I'll close it.
